const vocabItemList = {
	chineseText: '水',
	transcript: 'shuǐ',
	levelCount: 1,
	description1: 'noun',
	description2: '水',
	description3: 'water',
}
export const familiarVocabItemsList = [
	{
		chineseText: '水',
		transcript: 'shuǐ',
		levelCount: 2,
		description1: 'noun',
		description2: '水',
		description3: 'water',
	},
	{
		chineseText: '河',
		transcript: 'shuǐ',
		levelCount: 3,
		description1: 'noun',
		description2: '水',
		description3: 'water',
	},
	{
		chineseText: '河流',
		transcript: 'shuǐ',
		levelCount: 4,
		description1: 'noun',
		description2: '水',
		description3: 'water',
	},
	{
		chineseText: '河谷',
		transcript: 'shuǐ',
		levelCount: 5,
		description1: 'noun',
		description2: '水',
		description3: 'water',
	},
	{
		chineseText: '河谷',
		transcript: 'shuǐ',
		levelCount: 6,
		description1: 'noun',
		description2: '水',
		description3: 'water',
	},
	{
		chineseText: '河谷',
		transcript: 'shuǐ',
		levelCount: 6,
		description1: 'noun',
		description2: '水',
		description3: 'water',
	},
	{
		chineseText: '河谷',
		transcript: 'shuǐ',
		levelCount: 1,
		description1: 'noun',
		description2: '水',
		description3: 'water',
	},
]
export const unFamiliarVocabItemsList = [
	{
		chineseText: '河',
		transcript: 'shuǐ',
		levelCount: 1,
		description1: 'noun',
		description2: '水',
		description3: 'water',
	},
	{
		chineseText: '水',
		transcript: 'shuǐ',
		levelCount: 2,
		description1: 'noun',
		description2: '水',
		description3: 'water',
	},
	{
		chineseText: '河流',
		transcript: 'shuǐ',
		levelCount: 4,
		description1: 'noun',
		description2: '水',
		description3: 'water',
	},
	{
		chineseText: '河谷',
		transcript: 'shuǐ',
		levelCount: 5,
		description1: 'noun',
		description2: '水',
		description3: 'water',
	},
	{
		chineseText: '河谷',
		transcript: 'shuǐ',
		levelCount: 6,
		description1: 'noun',
		description2: '水',
		description3: 'water',
	},
	{
		chineseText: '河谷',
		transcript: 'shuǐ',
		levelCount: 6,
		description1: 'noun',
		description2: '水',
		description3: 'water',
	},
	{
		chineseText: '河谷',
		transcript: 'shuǐ',
		levelCount: 1,
		description1: 'noun',
		description2: '水',
		description3: 'water',
	},
]
